openapi: 3.0.4

info:
  title: Social Network - System Design Course
  description: API социальной сети для путешественников
  version: 1.0.0

tags:
  - name: post
    description: Действия над постами
  - name: photo
    description: Действия над фотографиями
  - name: user
    description: Действия с пользователем
paths:
  /post:
    post:
      tags:
        - post
      summary: Добавление нового поста
      description: Добавление нового поста с описанием, фотографиями и привязкой к месту путешествия
      requestBody:
        description: Создание нового поста
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
            examples:
              request:
                value:
                  id: 2843614705
                  user_id: 482953816921
                  text: "Путешествие в Африку в декабре этого года"
                  location: "Нгоронгоро, Танзания"
                  photos: []
        required: true
      responses:
        '204':
          description: Успешное добавление поста
        '400':
          description: Некорректный запрос
        '405':
          description: Метод не поддерживается
        '409':
          description: Конфликт
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                response:
                  value:
                    code: "E.4001.001"
                    details:
                      target: "id"
                      message: "Некорректный формат"
        '5XX':
          description: Ошибка сервера
  /post/{id}/reaction:
    post:
      tags:
        - post
      summary: Добавление реакции к посту
      description: Добавление реакции к посту
      parameters:
        - name: id
          in: path
          description: id поста
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Добавление реакции к посту
        content:
          application/json:
            schema:
              type: object
              properties:
                reaction_id:
                  type: integer
                  format: int32
                  description: id реакции из справочника
                user_id:
                  type: integer
                  format: int64
                  description: id пользователя, давшего оценку
              required:
                - reaction_id
                - user_id
            examples:
              request:
                value:
                  reaction_id: 12
                  user_id: 482953816921
        required: true
      responses:
        '204':
          description: Успешное добавление реакции
        '400':
          description: Некорректный запрос
        '404':
          description: Пост не найден
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                response:
                  value:
                    code: "E.4001.001"
                    details:
                      target: "id"
                      message: "Некорректный формат"
        '5XX':
          description: Ошибка сервера
  /post/{id}/comment:
    post:
      tags:
        - post
      summary: Комментирование поста
      description: Добавление комментария к посту
      parameters:
        - name: id
          in: path
          description: id поста
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Добавление комментария к посту
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  format: int64
                  description: id пользователя, добавившего комментарий
                text:
                  type: string
                  maxLength: 1500
                  description: текст комментария
              required:
                - user_id
                - text
            examples:
              request:
                value:
                  user_id: 482953816921
                  text: "Я останавливался в этом же отеле год назад."
        required: true
      responses:
        '204':
          description: Успешное добавление комментария
        '400':
          description: Некорректный запрос
        '404':
          description: Пост не найден
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                response:
                  value:
                    code: "E.4001.001"
                    details:
                      target: "id"
                      message: "Некорректный формат"
        '5XX':
          description: Ошибка сервера
  /post/{id}/comments:
    get:
      tags:
        - post
      summary: Получение комментариев для поста
      description: Получение комментариев для поста
      parameters:
        - name: id
          in: path
          description: id поста
          required: true
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: количество комментариев
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: номер страницы с результатами
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Массив комментариев
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      description: id комментария
                      example: 5379031472
                    text:
                      type: string
                      description: текст комментария
                    user_id:
                      type: integer
                      format: int64
                      description: пользователь, добавивший комментарий
                      example: 482953816921
                    created_at:
                      type: integer
                      format: int64
                      description: время добавления в миллисекундах
                      example: 1760299494000
        '404':
          description: Пост не найден
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                response:
                  value:
                    code: "E.4001.002"
                    details:
                      target: "limit"
                      message: "Значение не может быть отрицательным"
        '5XX':
          description: Ошибка сервера
  /post/{id}/reactions:
    get:
      tags:
        - post
      summary: Подсчет реакций для поста
      description: Подсчет реакций для поста
      parameters:
        - name: id
          in: path
          description: id поста
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Массив реакций с указанием кол-ва пользователей, выбравших реакцию
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reaction_id:
                      type: integer
                      format: int32
                      description: id реакции из справочника
                    count:
                      type: integer
                      description: сколько пользователей выбрало реакцию
                      example: 172
        '404':
          description: Пост не найден
        '5XX':
          description: Ошибка сервера
  /post/{id}/photos:
    get:
      tags:
        - post
      summary: Получение всех фотографий для поста
      description: Получение всех фотографий для поста
      parameters:
        - name: id
          in: path
          description: id поста
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Массив фотографий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Photo'
        '404':
          description: Пост не найден
        '5XX':
          description: Ошибка сервера
  /post/popularDestinations:
    get:
      tags:
        - post
      summary: Поиск популярных мест для путешествий
      description: Поиск популярных мест для путешествий
      parameters:
        - name: limit
          in: query
          description: количество постов
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: номер страницы с результатами
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Массив постов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                response:
                  value:
                    code: "E.4001.002"
                    details:
                      target: "limit"
                      message: "Значение не может быть отрицательным"
        '5XX':
          description: Ошибка сервера
  /photo:
    post:
      tags:
        - photo
      summary: Добавление фотографии
      description: Добавление фотографии
      requestBody:
        description: Добавление фотографии
        content:
          image/png:
            schema:
              type: string
              format: binary
        required: true
      responses:
        '200':
          description: Успешное добавление фотографии
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: id фотографии
                required:
                  - id
              examples:
                response:
                  value:
                    id: 2843614705
        '413':
          description: Слишком большой запрос
        '415':
          description: Неподдерживаемый тип медиа
        '5XX':
          description: Ошибка сервера
  /photo/{id}:
    get:
      tags:
        - photo
      summary: Скачивание фотографии по id
      description: Скачивание фотографии
      parameters:
        - name: id
          in: path
          description: id фотографии
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Фотография
          content:
            image/png:
              schema:
                $ref: '#/components/schemas/Photo'
        '404':
          description: Фотография не найдена
        '5XX':
          description: Ошибка сервера
  /user/{id}/follow:
    post:
      tags:
        - user
      summary: Подписка на пользователя
      description: Подписка на пользователя
      parameters:
        - name: id
          in: path
          description: id подписчика
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Подписка на пользователя
        content:
          application/json:
            schema:
              type: object
              properties:
                followed_user_id:
                  type: integer
                  format: int64
                  description: id пользователя, на которого подписываются
              required:
                - followed_user_id
            examples:
              request:
                value:
                  followed_user_id: 482953816921
        required: true
      responses:
        '204':
          description: Успешное добавление подписки
        '400':
          description: Некорректный запрос
        '404':
          description: Пользователь не найден
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                response:
                  value:
                    code: "E.4001.001"
                    details:
                      target: "id"
                      message: "Некорректный формат"
        '5XX':
          description: Ошибка сервера
  /user/{id}/posts:
    get:
      tags:
        - user
      summary: Получение постов для пользователя
      description: Получение постов для пользователя
      parameters:
        - name: id
          in: path
          description: id пользователя
          required: true
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: количество постов
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: номер страницы с результатами
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Массив постов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '404':
          description: Пользователь не найден
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                response:
                  value:
                    code: "E.4001.001"
                    details:
                      target: "id"
                      message: "Некорректный формат"
        '5XX':
          description: Ошибка сервера
  /user/{id}/subscriptions/posts:
    get:
      tags:
        - user
      summary: Получение постов из подписок пользователя
      description: Получение постов из подписок пользователя
      parameters:
        - name: id
          in: path
          description: id пользователя
          required: true
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: количество постов
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: номер страницы с результатами
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Массив постов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '404':
          description: Пользователь не найден
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                response:
                  value:
                    code: "E.4001.001"
                    details:
                      target: "id"
                      message: "Некорректный формат"
        '5XX':
          description: Ошибка сервера
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: id поста
          example: 2843614705
        user_id:
          type: integer
          format: int64
          description: id пользователя
          example: 482953816921
        text:
          type: string
          description: текст поста
          maxLength: 2200
          example: Путешествие в Африку в декабре этого года
        location:
          type: string
          description: место путешествия
          maxLength: 512
          example: Нгоронгоро, Танзания
        created_at:
          type: integer
          format: int64
          description: время добавления в миллисекундах
          example: 1760299494000
        photos:
          type: array
          description: массив фотографий
          items:
            $ref: '#/components/schemas/Photo'
          minItems: 0
          maxItems: 10
      required:
        - id
        - user_id
        - text
        - location
    Photo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: id фотографии
          example: 5379031472
        image:
          type: string
          format: binary
          description: фотография
      required:
        - id
        - image
    Error:
      type: object
      properties:
        code:
          type: string
          description: код ошибки
        details:
          type: object
          properties:
            target:
              type: string
              description: поле, вызвавшее ошибку валидации
            message:
              type: string
              description: сообщение об ошибке
          required:
            - target
            - message